In [1]:
#1. Import Numpy
import numpy as np

In [10]:
#2. Manually create a matrix: Create a 3-by-5 matrix and print it out to the screen
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]) 
a.shape = (3,5) 
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
#3. Manually create a vector: Create a vector which has 10 elements and print it out to the screen
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#4.1 Automatically create a 3-by-5 matrix which has interger values in the range of [0, 100]
a = np.random.randint(0,100,[3,5])
a

array([[19, 70, 19, 39, 90],
       [16, 82, 37,  4, 19],
       [81, 94, 74, 34, 72]])

In [13]:
#4.2 Automatically create a 5-by-7 matrix which has interger values in the range of [0, 100]
b = np.random.randint(0,100,[5,7])
b

array([[24, 40, 56, 64, 47, 23, 63],
       [37, 38, 58, 30, 87, 53, 30],
       [84, 93, 57, 69, 85, 90, 74],
       [87, 35, 77, 59,  2, 15, 30],
       [86, 39, 89, 64, 33, 12, 50]])

In [15]:
#4.4 Implementy matrix multiplication of the above 2 matrices and print the result to the screen (let us call this result matrixx is C)
c = a*b
c

array([[1272, 3120, 1008, 5952, 3713, 2047, 4158],
       [1665,  798, 4466, 1980, 8439, 5194, 1500],
       [7392, 5301,  456,  828, 3825, 3150, 7178],
       [ 696, 1435, 7084,  708,   94,  945, 1950],
       [ 688, 3081, 5073, 1408,  891,   84, 3500]])

In [16]:
#5. Scalar multiplication:
n = int(input("Random number from keyboard = "))

Random number from keyboard = 2


In [20]:
d = n * c
d

array([[ 2544,  6240,  2016, 11904,  7426,  4094,  8316],
       [ 3330,  1596,  8932,  3960, 16878, 10388,  3000],
       [14784, 10602,   912,  1656,  7650,  6300, 14356],
       [ 1392,  2870, 14168,  1416,   188,  1890,  3900],
       [ 1376,  6162, 10146,  2816,  1782,   168,  7000]])

In [23]:
#6. Automatically create vector. Automattically create a vector at size of 7-by-1 which has values in the range of [-10, 30]. And multiply the C matrix with this vector. Print the result to the screen.
e = np.random.randint(-10,30,(7,1))
e

array([[ 4],
       [ 6],
       [-4],
       [19],
       [ 7],
       [21],
       [23]])

In [26]:
y = c.dot(e)
y

array([[297476],
       [233851],
       [333301],
       [ 61863],
       [116199]])

In [36]:
#7. Matrix slicing
#7.1 Automatically create a matrix at size of 7-by-15
z = np.random.rand(7,15)
z

array([[0.37217062, 0.00807048, 0.60283806, 0.16857938, 0.46721333,
        0.48190974, 0.66399973, 0.84440435, 0.68954135, 0.0313227 ,
        0.56107109, 0.50525358, 0.32424353, 0.72558523, 0.24243665],
       [0.22319053, 0.52601526, 0.99179508, 0.79817757, 0.41430458,
        0.86369638, 0.28473335, 0.9047283 , 0.93992564, 0.94144952,
        0.92769151, 0.12047167, 0.69533639, 0.35595344, 0.73876027],
       [0.6773824 , 0.44071965, 0.5556412 , 0.03849614, 0.50452704,
        0.68632035, 0.70763908, 0.06821518, 0.52325325, 0.26051071,
        0.741366  , 0.75377748, 0.70333491, 0.72972336, 0.61967446],
       [0.96150757, 0.60130909, 0.07407014, 0.11785897, 0.18284149,
        0.89804645, 0.65980067, 0.6698433 , 0.13398754, 0.29560795,
        0.56234813, 0.43652183, 0.08012968, 0.12758029, 0.32728152],
       [0.18357819, 0.65889904, 0.96402764, 0.23926402, 0.48843266,
        0.83549309, 0.93764874, 0.82891375, 0.70030826, 0.57356575,
        0.58228544, 0.23582501, 0.09789159, 

In [40]:
#7.2 Print out the first column of this matrix
z[...,0] 

array([0.37217062, 0.22319053, 0.6773824 , 0.96150757, 0.18357819,
       0.05894459, 0.78862157])

In [41]:
#7.3 Print out the third row of this matrix
z[2,...] 

array([0.6773824 , 0.44071965, 0.5556412 , 0.03849614, 0.50452704,
       0.68632035, 0.70763908, 0.06821518, 0.52325325, 0.26051071,
       0.741366  , 0.75377748, 0.70333491, 0.72972336, 0.61967446])

In [42]:
#7.4 Print out the element at the second column and fourth row
z[3,1] 

0.6013090928957572

In [43]:
#8. Matrix transposition. Perform the matrix transposition of the matrix in question 7 and print out to the screen.
w = z.T
w

array([[0.37217062, 0.22319053, 0.6773824 , 0.96150757, 0.18357819,
        0.05894459, 0.78862157],
       [0.00807048, 0.52601526, 0.44071965, 0.60130909, 0.65889904,
        0.3305528 , 0.43794069],
       [0.60283806, 0.99179508, 0.5556412 , 0.07407014, 0.96402764,
        0.86612072, 0.07694073],
       [0.16857938, 0.79817757, 0.03849614, 0.11785897, 0.23926402,
        0.35567447, 0.32308056],
       [0.46721333, 0.41430458, 0.50452704, 0.18284149, 0.48843266,
        0.65798548, 0.57801247],
       [0.48190974, 0.86369638, 0.68632035, 0.89804645, 0.83549309,
        0.6175515 , 0.2062981 ],
       [0.66399973, 0.28473335, 0.70763908, 0.65980067, 0.93764874,
        0.21279721, 0.6279913 ],
       [0.84440435, 0.9047283 , 0.06821518, 0.6698433 , 0.82891375,
        0.58021573, 0.94110925],
       [0.68954135, 0.93992564, 0.52325325, 0.13398754, 0.70030826,
        0.1090475 , 0.25937608],
       [0.0313227 , 0.94144952, 0.26051071, 0.29560795, 0.57356575,
        0.00247392, 0.2

In [49]:
#9. Matrix addition. Automatically create 2 integer matrices whicch have values in the range of [-10, 30]
j = np.random.randint(-10,30,[2,3])
j

array([[-9, 16, 16],
       [-2, 13, 16]])

In [52]:
k = np.random.randint(-10,30,[2,3])
k

array([[ 3, 11, 20],
       [13, -4,  4]])

In [53]:
#9.3 Perform matrix addition of the above 2 matrices and print the result to the screen.
g = j + k
g

array([[-6, 27, 36],
       [11,  9, 20]])